/**
 * `@jonny-boi/cards` — the playable card pool as DATA + the effect-primitive
 * library that the pool's cards reference (DESIGN §3.2).
 *
 * A card is a `CardDefinition` data record; an effect is a small pure
 * `EffectPrimitive` registered by id (`./primitives`). There is no
 * class-per-card. The pool has two halves and they are the same shape:
 * hand-authored cards (`../data/pool`) and cards the Oracle-text compiler built
 * from their real Scryfall text (`../data/expanded-pool`, generated). A card
 * only joins the compiled half if the compiler judged it `'complete'` — every
 * printed ability genuinely implemented — so nothing in the pool is an
 * approximation. What the compiler refused, and why, is in
 * `../data/expansion-report.json`.
 *
 * Other packages consume this through:
 *
 *   - `loadCardPool()` → a validated, indexed pool (lookup by Scryfall id/name).
 *   - `buildRegistry()` → an `EffectRegistry` with every primitive registered,
 *     ready for `createEngine(config, registry)` / `createGame({ …, registry })`.
 *   - `getCardWithRegistry(id)` → a `{ card, registry }` bundle ready to play.
 *
 * JOIN KEY to `data-tools`: a card's `id` is its Scryfall id (UUID) in
 * `packages/data-tools/data/card-index.json`; `name` is the secondary key.
 */

/** Stable package identity placeholder retained for the cross-workspace smoke test. */
export const PACKAGE_NAME = 'cards';

// Effect-primitive library (the §2 effect seam).
export {
  registerCoreEffects,
  CORE_PRIMITIVES,
  CORE_PRIMITIVE_IDS,
  dealDamage,
  drawCards,
  gainLife,
  loseLife,
  pumpUntilEndOfTurn,
  grantKeywordUntilEndOfTurn,
  makeToken,
  persistReturn,
  destroyTarget,
  exileTarget,
  destroyAll,
  addMana,
  counterSpell,
  createToken,
  tapTarget,
  attachToTarget,
} from './primitives.js';

// The choice-driven primitives (DESIGN §3.11): the ones that ask the player a
// question mid-resolution instead of guessing for them.
export {
  CHOICE_PRIMITIVES,
  putFromHandOnTop,
  reorderTopOfLibrary,
  mayShuffleLibrary,
  searchLibrary,
  revealTopCard,
  discardCard,
  returnFromGraveyard,
  modal,
  returnToHand,
  tapPermanents,
  counterUnlessPaid,
} from './choice-primitives.js';

// Pool loader + registry builder.
export type { AttachmentProblem, CardPool, UnsupportedRef } from './pool.js';
export {
  loadCardPool,
  getCardDefinition,
  buildRegistry,
  getCardWithRegistry,
} from './pool.js';

// The raw data (read-only) for tooling/UI that wants the whole list.
// `CARD_POOL` is everything; the two halves are exported for tooling that cares
// how a card was authored — `CURATED_CARD_POOL` is hand-written and reviewed
// against the engine, `EXPANDED_CARD_POOL` is generated by the Oracle compiler
// from real Scryfall text (see `../scripts/build-expansion.ts`). They play
// identically; only their provenance differs.
export { CARD_POOL, CURATED_CARD_POOL, BASIC_LAND_NAMES } from '../data/pool.js';
export { EXPANDED_CARD_POOL } from '../data/expanded-pool.js';

// Oracle-text compiler — import ANY real card as a genuine engine definition, or
// get an honest list of the engine systems it would still need (`./compile`).
export type {
  CompilableCard,
  CompileResult,
  CompileStatus,
  UnsupportedClause,
} from './compile/index.js';
export { compileCard, compileCards, explainUnsupported } from './compile/index.js';

// The compiler's own live registries, re-exported for the About view: the rule
// tables and keyword map say what imports as fully playable TODAY, and the
// hint list + system-less types are its honest TODO. Reading them here (rather
// than keeping a prose copy) is what keeps that page correct by construction.
export type { CompileRule } from './compile/index.js';
export {
  EFFECT_RULES,
  TRIGGER_RULES,
  MANA_RULES,
  STATIC_RULES,
  KEYWORD_FLAGS,
  UNSUPPORTED_HINTS,
  TYPES_WITHOUT_SYSTEM,
} from './compile/index.js';

/**
 * Mechanics intentionally stubbed because the engine lacks the system to model them
 * faithfully. Each listed card still LOADS and PLAYS (correct cost, zone, P/T,
 * keywords, mana production); only the listed sub-mechanic is omitted. This is the
 * honest record referenced by `../data/pool`'s header.
 *
 * The rule this list exists to enforce: **faithful or not at all**. A card that
 * cannot be played correctly stays here with the precise system it is waiting for,
 * because a card that plays *nearly* right silently corrupts every A/B verdict that
 * includes it.
 *
 * Un-stubbed by the player-choice system (DESIGN §3.11) — these now play for real,
 * asking their questions through `pendingChoice`: **Brainstorm** (ordered put-back),
 * **Ponder** (top-3 reorder + optional shuffle), **Thoughtseize** (caster picks the
 * victim's nonland card), **Eternal Witness** (chosen graveyard card), **Cryptic
 * Command** (all four modes, choose two), **Path to Exile** (the controller's
 * optional basic-land search) and **Goblin Guide** (reveal the top card, take it
 * only if it is a land). Earlier waves un-stubbed Young Pyromancer, Monastery
 * Swiftspear, Kitchen Finks and Giant Growth on the trigger + continuous layers.
 */
export const STUBBED_MECHANICS: ReadonlyArray<{
  readonly card: string;
  readonly missingEngineSystem: string;
}> = Object.freeze([
  { card: 'Delver of Secrets', missingEngineSystem: 'transform (upkeep reveal + flip to a 3/2 flyer)' },
  {
    // Flash timing AND flashback-the-mechanic both exist now (`castTiming` reads
    // flash; `CardDefinition.flashback` casts from the graveyard and exiles on
    // leaving the stack). What Snapcaster still needs is the GRANT: targeting an
    // instant/sorcery card in a graveyard (targeting reaches only permanents,
    // players and spells today) and a continuous effect that gives a
    // NON-battlefield card a flashback cost derived from its mana cost, until end
    // of turn. Un-stub it only when a trigger can aim at a graveyard card and the
    // continuous layer can carry a grant on one.
    card: 'Snapcaster Mage',
    missingEngineSystem:
      'granting flashback to a card in a graveyard (targeting a graveyard card + a continuous effect on a non-battlefield card)',
  },
  {
    card: 'Sakura-Tribe Elder',
    missingEngineSystem: 'activated abilities with a sacrifice cost (the basic-land search itself is now expressible)',
  },
  { card: 'Tarmogoyf', missingEngineSystem: 'dynamic */*+1 P/T derived from graveyard card types' },
  { card: 'Liliana of the Veil', missingEngineSystem: 'planeswalker loyalty abilities' },
  {
    card: 'Fatal Push',
    missingEngineSystem: 'revolt — a "a permanent you controlled left the battlefield this turn" tracker for the ≤4 mode',
  },
  {
    // Everything Cryptic DOES is faithful; what is early is WHEN it is decided.
    card: 'Cryptic Command',
    missingEngineSystem:
      'modes are chosen on resolution, not at cast: core picks targets at cast with no mode declared, so a mode is offered only when this cast happens to have a legal target for it (needs mode+target selection at cast time)',
  },
]);
