/**
 * `@jonny-boi/cards` — the playable card pool as DATA + the effect-primitive
 * library that the pool's cards reference (DESIGN §3.2).
 *
 * A card is a `CardDefinition` data record; an effect is a small pure
 * `EffectPrimitive` registered by id (`./primitives`). There is no
 * class-per-card. The pool has two halves and they are the same shape:
 * hand-authored cards (`../data/pool`) and cards the Oracle-text compiler built
 * from their real Scryfall text (`../data/expanded-pool`, generated). A card
 * only joins the compiled half if the compiler judged it `'complete'` — every
 * printed ability genuinely implemented — so nothing in the pool is an
 * approximation. What the compiler refused, and why, is in
 * `../data/expansion-report.json`.
 *
 * Other packages consume this through:
 *
 *   - `loadCardPool()` → a validated, indexed pool (lookup by Scryfall id/name).
 *   - `buildRegistry()` → an `EffectRegistry` with every primitive registered,
 *     ready for `createEngine(config, registry)` / `createGame({ …, registry })`.
 *   - `getCardWithRegistry(id)` → a `{ card, registry }` bundle ready to play.
 *
 * JOIN KEY to `data-tools`: a card's `id` is its Scryfall id (UUID) in
 * `packages/data-tools/data/card-index.json`; `name` is the secondary key.
 */

/** Stable package identity placeholder retained for the cross-workspace smoke test. */
export const PACKAGE_NAME = 'cards';

// Effect-primitive library (the §2 effect seam).
export {
  registerCoreEffects,
  CORE_PRIMITIVES,
  CORE_PRIMITIVE_IDS,
  dealDamage,
  drawCards,
  gainLife,
  loseLife,
  pumpUntilEndOfTurn,
  grantKeywordUntilEndOfTurn,
  grantKeywordToYoursUntilEndOfTurn,
  modifyYoursUntilEndOfTurn,
  makeToken,
  persistReturn,
  destroyTarget,
  exileTarget,
  destroyAll,
  addMana,
  counterSpell,
  createToken,
  tapTarget,
  attachToTarget,
  ifKicked,
  grantFlashback,
  ITS_MANA_COST,
} from './primitives.js';

// The choice-driven primitives (DESIGN §3.11): the ones that ask the player a
// question mid-resolution instead of guessing for them.
export {
  CHOICE_PRIMITIVES,
  putFromHandOnTop,
  handToBottomThenDraw,
  reorderTopOfLibrary,
  mayShuffleLibrary,
  searchLibrary,
  revealTopCard,
  discardCard,
  returnFromGraveyard,
  returnToHand,
  tapPermanents,
  counterUnlessPaid,
  sacrificeChosen,
  pileSplitSacrifice,
  transformRevealTop,
} from './choice-primitives.js';

// Pool loader + registry builder.
export type { AttachmentProblem, CardPool, UnsupportedRef } from './pool.js';
export {
  loadCardPool,
  getCardDefinition,
  buildRegistry,
  getCardWithRegistry,
} from './pool.js';

// The raw data (read-only) for tooling/UI that wants the whole list.
// `CARD_POOL` is everything; the two halves are exported for tooling that cares
// how a card was authored — `CURATED_CARD_POOL` is hand-written and reviewed
// against the engine, `EXPANDED_CARD_POOL` is generated by the Oracle compiler
// from real Scryfall text (see `../scripts/build-expansion.ts`). They play
// identically; only their provenance differs.
export { CARD_POOL, CURATED_CARD_POOL, BASIC_LAND_NAMES } from '../data/pool.js';
export { EXPANDED_CARD_POOL } from '../data/expanded-pool.js';

// Oracle-text compiler — import ANY real card as a genuine engine definition, or
// get an honest list of the engine systems it would still need (`./compile`).
export type {
  CompilableCard,
  CompilableCardFace,
  CompileResult,
  CompileStatus,
  UnsupportedClause,
} from './compile/index.js';
export {
  compileCard,
  compileCards,
  explainUnsupported,
  BACK_FACE_ID_SUFFIX,
  SECOND_CASTABLE_FACE_GAP,
  UNPAYABLE_MANA_SYMBOL_GAP,
  FUSE_GAP,
  ROOM_DOOR_GAP,
} from './compile/index.js';

// The compiler's own live registries, re-exported for the About view: the rule
// tables and keyword map say what imports as fully playable TODAY, and the
// hint list + system-less types are its honest TODO. Reading them here (rather
// than keeping a prose copy) is what keeps that page correct by construction.
export type { CompileRule } from './compile/index.js';
export {
  EFFECT_RULES,
  TRIGGER_RULES,
  MANA_RULES,
  STATIC_RULES,
  KEYWORD_FLAGS,
  UNSUPPORTED_HINTS,
  TYPES_WITHOUT_SYSTEM,
} from './compile/index.js';

/**
 * Mechanics intentionally stubbed because the engine lacks the system to model them
 * faithfully. Each listed card still LOADS and PLAYS (correct cost, zone, P/T,
 * keywords, mana production); only the listed sub-mechanic is omitted. This is the
 * honest record referenced by `../data/pool`'s header.
 *
 * The rule this list exists to enforce: **faithful or not at all**. A card that
 * cannot be played correctly stays here with the precise system it is waiting for,
 * because a card that plays *nearly* right silently corrupts every A/B verdict that
 * includes it.
 *
 * ## THE LIST IS NOW EMPTY, and that is the point of keeping it
 * Every hand-authored pool card plays as printed. The list stays — with its
 * whole history below — because it is the mechanism, not the content: the next
 * card the pool cannot model faithfully belongs HERE, named, rather than being
 * quietly shipped as an approximation. `fidelity.test.ts` audits every pool card
 * against its real Oracle text and skips exactly the cards named here, so an
 * empty list means the audit now covers the entire pool with no exemptions.
 *
 * Un-stubbed by the player-choice system (DESIGN §3.11) — these now play for real,
 * asking their questions through `pendingChoice`: **Brainstorm** (ordered put-back),
 * **Ponder** (top-3 reorder + optional shuffle), **Thoughtseize** (caster picks the
 * victim's nonland card), **Eternal Witness** (chosen graveyard card), **Path to Exile** (the controller's
 * optional basic-land search) and **Goblin Guide** (reveal the top card, take it
 * only if it is a land). Earlier waves un-stubbed Young Pyromancer, Monastery
 * Swiftspear, Kitchen Finks and Giant Growth on the trigger + continuous layers.
 * **Sakura-Tribe Elder** was un-stubbed by the template-gap pass: its sacrifice-
 * self activation cost and its basic-land search both existed already, and only
 * the "search … for a basic land card" compiler rule was missing.
 * The second-face system (CardDefinition.backFace + core's transformPermanent)
 * un-stubbed **Delver of Secrets** — both faces play as printed, upkeep reveal
 * included.
 * The planeswalker system un-stubbed **Liliana of the Veil** — all three loyalty
 * abilities play as printed (each-player discard, the edict, the pile split).
 * The CAST-TIME modal system un-stubbed **Cryptic Command** — all four modes,
 * chosen (and aimed) as the spell is cast, per CR 601.2b/c, so the opponent
 * decides whether to respond already knowing which two halves are coming.
 * The graveyard-grant system (targeting a card in a graveyard + core's
 * `card-grants.ts` layer) un-stubbed **Snapcaster Mage** — flash, the targeted
 * ETB, and the granted flashback all play as printed, and the granted cast goes
 * through the very same path a printed "Flashback {cost}" uses.
 * Characteristic-defining P/T (CR 613.3 layer 7a) un-stubbed **Tarmogoyf** — its
 * star box is the real formula over card types in all graveyards, re-derived on
 * every read; and the turn-scoped fact memory un-stubbed **Fatal Push**, whose
 * revolt mode now reads "a permanent you controlled left the battlefield this
 * turn" at resolution. The CAST-TIME MODAL system took the last entry off this
 * list, un-stubbing **Cryptic Command**: all four modes, announced AND aimed as
 * the spell is cast (CR 601.2b/c), so the opponent decides whether to respond
 * already knowing which two halves are coming.
 */
export const STUBBED_MECHANICS: ReadonlyArray<{
  readonly card: string;
  readonly missingEngineSystem: string;
}> = Object.freeze([]);
