/**
 * `@jonny-boi/cards` — the playable card pool as DATA + the effect-primitive
 * library that the pool's cards reference (DESIGN §3.2).
 *
 * A card is a `CardDefinition` data record; an effect is a small pure
 * `EffectPrimitive` registered by id (`./primitives`). There is no
 * class-per-card. The pool has two halves and they are the same shape:
 * hand-authored cards (`../data/pool`) and cards the Oracle-text compiler built
 * from their real Scryfall text (`../data/expanded-pool`, generated). A card
 * only joins the compiled half if the compiler judged it `'complete'` — every
 * printed ability genuinely implemented — so nothing in the pool is an
 * approximation. What the compiler refused, and why, is in
 * `../data/expansion-report.json`.
 *
 * Other packages consume this through:
 *
 *   - `loadCardPool()` → a validated, indexed pool (lookup by Scryfall id/name).
 *   - `buildRegistry()` → an `EffectRegistry` with every primitive registered,
 *     ready for `createEngine(config, registry)` / `createGame({ …, registry })`.
 *   - `getCardWithRegistry(id)` → a `{ card, registry }` bundle ready to play.
 *
 * JOIN KEY to `data-tools`: a card's `id` is its Scryfall id (UUID) in
 * `packages/data-tools/data/card-index.json`; `name` is the secondary key.
 */

/** Stable package identity placeholder retained for the cross-workspace smoke test. */
export const PACKAGE_NAME = 'cards';

// Effect-primitive library (the §2 effect seam).
export {
  registerCoreEffects,
  CORE_PRIMITIVES,
  CORE_PRIMITIVE_IDS,
  dealDamage,
  drawCards,
  gainLife,
  loseLife,
  pumpUntilEndOfTurn,
  grantKeywordUntilEndOfTurn,
  makeToken,
  persistReturn,
  destroyTarget,
  exileTarget,
  destroyAll,
  addMana,
  counterSpell,
  discardCard,
  createToken,
  tapTarget,
  returnFromGraveyard,
} from './primitives.js';

// Pool loader + registry builder.
export type { CardPool, UnsupportedRef } from './pool.js';
export {
  loadCardPool,
  getCardDefinition,
  buildRegistry,
  getCardWithRegistry,
} from './pool.js';

// The raw data (read-only) for tooling/UI that wants the whole list.
// `CARD_POOL` is everything; the two halves are exported for tooling that cares
// how a card was authored — `CURATED_CARD_POOL` is hand-written and reviewed
// against the engine, `EXPANDED_CARD_POOL` is generated by the Oracle compiler
// from real Scryfall text (see `../scripts/build-expansion.ts`). They play
// identically; only their provenance differs.
export { CARD_POOL, CURATED_CARD_POOL } from '../data/pool.js';
export { EXPANDED_CARD_POOL } from '../data/expanded-pool.js';

// Oracle-text compiler — import ANY real card as a genuine engine definition, or
// get an honest list of the engine systems it would still need (`./compile`).
export type {
  CompilableCard,
  CompileResult,
  CompileStatus,
  UnsupportedClause,
} from './compile/index.js';
export { compileCard, compileCards, explainUnsupported } from './compile/index.js';

/**
 * Mechanics intentionally stubbed because the engine (even with v2's triggers +
 * until-end-of-turn continuous effects, DESIGN §3.9) lacks the system to model them
 * faithfully. Each listed card still LOADS and PLAYS (correct cost, zone, P/T,
 * keywords, mana production); only the listed sub-mechanic is omitted. This is the
 * honest record referenced by `../data/pool`'s header.
 *
 * Engine-v2 un-stubbed (now wired onto real triggers + continuous effects, no longer
 * here): Young Pyromancer (cast-trigger tokens), Monastery Swiftspear (prowess),
 * Goblin Guide (attack trigger — approximated; see its data comment), and Kitchen
 * Finks (ETB lifegain + persist death-return). Giant Growth's pump now uses the real
 * until-EOT layer and wears off at cleanup. The cards below stay stubbed because
 * their missing system (planeswalker loyalty, transform/DFC, dynamic P/T, flash +
 * flashback, search/selection, modal choices) is genuinely not yet in the engine —
 * we do NOT fake those.
 */
export const STUBBED_MECHANICS: ReadonlyArray<{
  readonly card: string;
  readonly missingEngineSystem: string;
}> = Object.freeze([
  { card: 'Delver of Secrets', missingEngineSystem: 'transform (upkeep look + flip to 3/2 flyer)' },
  { card: 'Snapcaster Mage', missingEngineSystem: 'flash timing + graveyard flashback recast' },
  { card: 'Sakura-Tribe Elder', missingEngineSystem: 'activated sacrifice ability + basic-land search' },
  { card: 'Tarmogoyf', missingEngineSystem: 'dynamic */*+1 P/T from graveyard card types' },
  { card: 'Liliana of the Veil', missingEngineSystem: 'planeswalker loyalty abilities' },
  { card: 'Fatal Push', missingEngineSystem: 'revolt (≤4 mode when a permanent left your battlefield)' },
  { card: 'Path to Exile', missingEngineSystem: 'controller may search for a basic land' },
  { card: 'Brainstorm', missingEngineSystem: 'put two cards back on top (hand ordering choice)' },
  { card: 'Ponder', missingEngineSystem: 'top-3 reorder / optional shuffle (selection)' },
  { card: 'Cryptic Command', missingEngineSystem: 'modal "choose two" (we author counter + draw)' },
  { card: 'Thoughtseize', missingEngineSystem: 'reveal hand + opponent-chosen nonland discard' },
  { card: 'Eternal Witness', missingEngineSystem: 'choose which graveyard card to return' },
  {
    card: 'Goblin Guide',
    missingEngineSystem: 'attack trigger reveals defender top card only-if-land (approximated as opponent draw)',
  },
]);
