/**
 * §3.148 — OBLIVION RING AND JOURNEY TO NOWHERE, PLAYED.
 *
 * The compile-side pin lives in `compile/targeted-trigger-templates.test.ts`. It
 * proves the ETB exile compiles to `exileUntilLeaves` rather than `exileTarget`.
 * It cannot prove the card WORKS, and the defect it guards against was invisible
 * to every compile-level check the repo had: Journey to Nowhere compiled
 * `'complete'`, shipped in the pool, and played as a one-way exile because the
 * two halves were never linked.
 *
 * So this drives the real action loop — cast the enchantment, answer its target
 * question, destroy it, and look at where the prisoner ended up. That is the
 * only reading that can tell a linked O-Ring from an unlinked one.
 *
 * The cards are COMPILED HERE from their printed Oracle text rather than read
 * out of the pool: the generated pool is regenerated by the integrator, not by
 * this branch, so the shipped `expanded-pool.ts` still holds the unlinked
 * Journey to Nowhere. Compiling the printed text is what this branch changed,
 * and it is what this test has to exercise.
 */
import { describe, expect, it } from 'vitest';
import type { CardDefinition, GameAction, GameState, InstanceId, PlayerId } from '@jonny-boi/core';
import { applyAction, createGame, DEFAULT_RULES, defaultAnswerFor } from '@jonny-boi/core';
import { compileCard } from './compile/index.js';
import type { CompilableCard } from './compile/index.js';
import { buildRegistry } from './pool.js';
import { CARD_POOL } from '../data/pool.js';

type Registry = ReturnType<typeof buildRegistry>;

const SEED = 31148;

function fromPool(name: string): CardDefinition {
  const found = CARD_POOL.find((entry) => entry.name === name);
  if (!found) throw new Error(`pool missing ${name}`);
  return found;
}

/** Compile a printed card and insist the compiler accepted every line of it. */
function compiled(name: string, oracleText: string, manaCost: CompilableCard['manaCost']): CardDefinition {
  const result = compileCard({
    id: `test:${name}`,
    name,
    manaCost,
    typeLine: { supertypes: [], types: ['Enchantment'], subtypes: [] },
    oracleText,
    power: null,
    toughness: null,
    keywords: [],
  } as CompilableCard);
  expect(result.status, `${name}: ${JSON.stringify(result.missing)}`).toBe('complete');
  return result.definition;
}

const WHITE_2 = { generic: 2, W: 1, U: 0, B: 0, R: 0, G: 0, C: 0, other: [] } as const;

const OBLIVION_RING = compiled(
  'Oblivion Ring',
  'When Oblivion Ring enters, exile another target nonland permanent.\n' +
    "When Oblivion Ring leaves the battlefield, return the exiled card to the battlefield under its owner's control.",
  WHITE_2,
);

const JOURNEY_TO_NOWHERE = compiled(
  'Journey to Nowhere',
  'When Journey to Nowhere enters, exile target creature.\n' +
    "When Journey to Nowhere leaves the battlefield, return the exiled card to the battlefield under its owner's control.",
  WHITE_2,
);

function act(state: GameState, action: GameAction, reg: Registry): GameState {
  const result = applyAction(state, action, DEFAULT_RULES, reg);
  const rejected = result.events.find((e) => e.type === 'actionRejected') as { reason?: string } | undefined;
  if (rejected) throw new Error(`unexpected rejection: ${rejected.reason ?? '?'}`);
  return result.state;
}

/** Settle the stack, answering anything asked with the given answer factory. */
function settle(
  state: GameState,
  reg: Registry,
  answer: (question: NonNullable<GameState['pendingChoice']>) => unknown = defaultAnswerFor,
): GameState {
  let s = state;
  let guard = 0;
  while ((s.stack.length > 0 || s.pendingChoice != null) && guard++ < 80) {
    const question = s.pendingChoice;
    s = question
      ? act(s, { kind: 'answerChoice', player: question.chooser, choiceId: question.id, answer: answer(question) } as GameAction, reg)
      : act(s, { kind: 'passPriority', player: s.priorityPlayer }, reg);
  }
  return s;
}

function toMain(reg: Registry): GameState {
  const forest = fromPool('Forest');
  const { state } = createGame({
    seed: SEED,
    decks: {
      A: { cards: Array.from({ length: 60 }, () => forest) },
      B: { cards: Array.from({ length: 60 }, () => forest) },
    },
    registry: reg,
  });
  let s = state;
  let guard = 0;
  while ((s.step !== 'precombatMain' || s.priorityPlayer !== 'A' || s.stack.length > 0 || s.pendingChoice) && guard++ < 600) {
    s = settle(s, reg);
    if (s.stack.length === 0 && s.pendingChoice == null) s = act(s, { kind: 'passPriority', player: s.priorityPlayer }, reg);
  }
  s.players.A.manaPool = { W: 9, U: 9, B: 9, R: 9, G: 9, C: 9 };
  s.players.B.manaPool = { W: 9, U: 9, B: 9, R: 9, G: 9, C: 9 };
  return s;
}

function put(state: GameState, def: CardDefinition, controller: PlayerId, zone: 'battlefield' | 'hand'): InstanceId {
  const id = state.nextInstanceId++;
  const instance = {
    instanceId: id,
    def,
    controller,
    owner: controller,
    zone,
    tapped: false,
    summoningSick: false,
    damageMarked: 0,
    markedByDeathtouch: false,
    attachedTo: null,
    counters: {},
  } as never;
  if (zone === 'hand') (state.players[controller].hand as unknown[]).push(instance);
  else (state.battlefield as unknown[]).push(instance);
  return id;
}

/** Cast a jail enchantment onto a chosen victim, and hand back the settled board. */
function jail(reg: Registry, jailer: CardDefinition, victim: CardDefinition): { state: GameState; ring: InstanceId; prisoner: InstanceId } {
  let s = toMain(reg);
  const prisoner = put(s, victim, 'B', 'battlefield');
  const ring = put(s, jailer, 'A', 'hand');
  s = act(s, { kind: 'castSpell', player: 'A', instanceId: ring, targets: [] }, reg);
  s = settle(s, reg, (question) =>
    question.kind === 'selectTargets' ? { kind: 'selectTargets', targets: [prisoner] } : defaultAnswerFor(question),
  );
  return { state: s, ring, prisoner };
}

describe('the O-Ring pair, played end to end', () => {
  it('Oblivion Ring exiles the chosen permanent and GIVES IT BACK when the Ring is destroyed', () => {
    const reg = buildRegistry();
    const bears = fromPool('Grizzly Bears');
    const jailed = jail(reg, OBLIVION_RING, bears);
    const { ring, prisoner } = jailed;
    let s = jailed.state;

    expect(s.battlefield.some((c) => c.instanceId === prisoner), 'the prisoner leaves the battlefield').toBe(false);
    expect(s.players.B.exile.some((c) => c.instanceId === prisoner), "to its OWNER's exile").toBe(true);

    // Destroy the Ring the way a player would — a real removal spell from the
    // pool, resolved through the action loop, so the `leaves` trigger is the
    // engine's and not this test's.
    const demystify = put(s, fromPool('Demystify'), 'A', 'hand');
    s = act(s, { kind: 'castSpell', player: 'A', instanceId: demystify, targets: [ring] }, reg);
    s = settle(s, reg);

    expect(s.battlefield.some((c) => c.instanceId === ring), 'the Ring is destroyed').toBe(false);
    const back = s.battlefield.find((c) => c.instanceId === prisoner);
    // ⚠️ THE DISCRIMINATOR. An UNLINKED exile (`exileTarget`) leaves this
    // undefined: the prisoner stays in exile for ever and the card is removal
    // with no drawback.
    expect(back, 'the prisoner comes back when the Ring leaves').toBeDefined();
    expect(back?.controller, "under its OWNER's control").toBe('B');
  });

  it('Journey to Nowhere — the card that shipped BROKEN — gives its prisoner back too', () => {
    const reg = buildRegistry();
    const jailed = jail(reg, JOURNEY_TO_NOWHERE, fromPool('Runeclaw Bear'));
    const { ring, prisoner } = jailed;
    let s = jailed.state;
    expect(s.players.B.exile.some((c) => c.instanceId === prisoner), 'the creature is exiled').toBe(true);

    const demystify = put(s, fromPool('Demystify'), 'A', 'hand');
    s = act(s, { kind: 'castSpell', player: 'A', instanceId: demystify, targets: [ring] }, reg);
    s = settle(s, reg);

    expect(
      s.battlefield.some((c) => c.instanceId === prisoner),
      'the whole point of the printed second line',
    ).toBe(true);
  });
});
