/**
 * THE DECKLISTS BEHIND THE PINNED SOAK ROWS (`soak.test.ts`).
 *
 * A pinned regression replays one game, and a game is (decks × seed). The decks
 * half used to be regenerated by sampling the pool from the seed — which meant
 * every pool change silently re-dealt every pinned row onto a different match.
 * Adding two cards in DESIGN §3.35 did exactly that to three of the four rows,
 * and an 8,000-game hunt with the fix reverted did not re-deal the copy mirror
 * once. A regression that cannot be re-found is a regression that has stopped
 * being tested.
 *
 * So the decks are recorded here, verbatim, as the generator produced them on
 * the day each bug was found. Card ids are Scryfall UUIDs and are stable across
 * pool churn — only the SAMPLING moved, never the cards themselves.
 *
 * ⚠️ Do not "tidy" these lists. They are evidence, not configuration: each one is
 * the exact 60 cards that produced a specific engine defect, and a card removed
 * from one is a row that can no longer prove its fix holds.
 */
import type { SoakDeck } from './soak-decks.js';

/** One pinned matchup: the two decklists a pinned seed originally dealt. */
export interface PinnedMatchup {
  readonly A: SoakDeck;
  readonly B: SoakDeck;
}

/**
 * HOW A TEST RECOGNISES THE GAME IT JUST REPLAYED — one answer, read by every
 * pinned row (`soak.test.ts`, `loop-runaway.test.ts`).
 *
 * "No violations" is also what a replay of the WRONG game reports, so an
 * outcome-only assertion is green for two completely different reasons. Every
 * pinned row asserts these card names are in the decklists it played BEFORE it
 * asserts anything about what happened. The list lives here rather than in each
 * test because it is a property of the MATCHUP, and two copies of it would
 * eventually disagree about which game a seed is.
 *
 * ⚠️ **NAME CARDS FROM BOTH DECKS.** A row whose identity cards all sit in one
 * deck survives a substitution of the other, and that is measured rather than
 * feared: seed 113343071 named only `Reverberate` and `Narset's Reversal`, both
 * in deck B, and swapping deck A for an unrelated pinned deck left the row fully
 * GREEN — still reporting the runaway it expected, from a match it was never
 * meant to play. Every entry below now names at least one card from each side,
 * and the deck it comes from is written next to it.
 */
export type PinnedIdentity = readonly string[];

/** Seed 4222011655. */
export const PINNED_4222011655: PinnedMatchup = {
  A: {
      name: "soak-mixed-4222011655",
      archetype: "soak/WB",
      seed: 4222011655,
      colors: ["W","B"],
      cards: [
        { cardId: "dd70d439-bd60-43d1-ac26-13b744cc4a37", count: 1 },
        { cardId: "98423a34-f044-4811-b288-56981d604b6e", count: 1 },
        { cardId: "97b477d8-2e05-475e-8ed6-7d680cb21cd9", count: 2 },
        { cardId: "bd9e416a-89b3-4912-be9b-49fce6a93dc9", count: 1 },
        { cardId: "4b7ac066-e5c7-43e6-9e7e-2739b24a905d", count: 4 },
        { cardId: "e462e78d-2d26-4a2d-8d8f-5f31abe5c924", count: 1 },
        { cardId: "8cdfd9df-4783-4138-a286-828a97f516aa", count: 3 },
        { cardId: "394fae8f-3757-4e08-b97c-5d7c451f4e72", count: 3 },
        { cardId: "b693c3de-2eaf-4850-b405-e79d00adefda", count: 2 },
        { cardId: "a02e1ca7-23c5-41e3-a744-72fc9e9dd8ba", count: 3 },
        { cardId: "f2ccc9e8-8e92-4f8c-8728-8c748630e0dd", count: 2 },
        { cardId: "42b2db4c-4a1d-436f-9eeb-53a04db46c58", count: 4 },
        { cardId: "452e3f5f-ce17-4682-966b-5cc100210aee", count: 4 },
        { cardId: "f62cabf0-df0d-4c4f-a93a-9340967d1775", count: 1 },
        { cardId: "310f141c-7f37-4729-aed6-dd9c09db448d", count: 2 },
        { cardId: "e6e6fce8-0f6a-4b84-865e-d4e4a4182f9f", count: 2 },
        { cardId: "2672e0ca-8d5c-449f-8483-35d0e697fbb2", count: 1 },
        { cardId: "a4580a1d-141e-449b-9018-e0258130634b", count: 1 },
        { cardId: "42bf259d-4bb9-49c3-b4ec-223dca62f4d6", count: 1 },
        { cardId: "a75445d3-1303-4bb5-89ad-26ea93fecd48", count: 4 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 7 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 10 },
      ],
    },
  B: {
      name: "soak-mixed--596499928",
      archetype: "soak/UB",
      seed: -596499928,
      colors: ["U","B"],
      cards: [
        { cardId: "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7", count: 1 },
        { cardId: "02500f21-6e15-423e-93ff-891e09fe9904", count: 4 },
        { cardId: "b166b670-febc-4821-855e-f8d465644c03", count: 2 },
        { cardId: "8fcf50cd-e6d0-4516-850f-d42ee75dcc3a", count: 1 },
        { cardId: "feb244f8-bcb1-44cf-9940-2719221a7309", count: 4 },
        { cardId: "59e7f2ae-4535-4191-98be-3e65b6b2befa", count: 1 },
        { cardId: "ed228f67-3adf-46d4-ac45-e0278592850d", count: 4 },
        { cardId: "f90fe86c-5cca-483b-93c2-6e856fa01c88", count: 3 },
        { cardId: "44c5f8e1-d9b8-4067-a60a-1ecc8bd11145", count: 1 },
        { cardId: "f07a24c0-bf3c-4733-9473-c6be3b16950e", count: 4 },
        { cardId: "23745133-e5e2-4ce3-b94a-73d0d3d8a013", count: 2 },
        { cardId: "77637eff-2963-4402-88f3-ca346f762fc8", count: 4 },
        { cardId: "3378fef3-4d8c-4d9e-a338-4abb6f70d410", count: 2 },
        { cardId: "c174dcbb-03a0-439c-b3d8-ed61bd46dc67", count: 1 },
        { cardId: "765863c8-1be0-4bb1-9e9c-db7701cffde3", count: 2 },
        { cardId: "868e6e68-4367-4073-a864-235d5961ae56", count: 4 },
        { cardId: "616d6013-24f4-4999-9bf3-5b0764e52fa6", count: 1 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 9 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 10 },
      ],
    },
};

/** Seed 1390617766. */
export const PINNED_1390617766: PinnedMatchup = {
  A: {
      name: "soak-mixed-1390617766",
      archetype: "soak/UB",
      seed: 1390617766,
      colors: ["U","B"],
      cards: [
        { cardId: "d569d969-ce39-4314-b5f0-76b45f5c4c7f", count: 2 },
        { cardId: "41c84665-1f99-40ab-aaca-1188649eb263", count: 3 },
        { cardId: "cde26d69-f3e7-4dd0-a53b-cd0ec812d717", count: 4 },
        { cardId: "a2529491-7389-4cfa-92d2-145eda779603", count: 3 },
        { cardId: "932708ae-9d5c-4561-aa8b-0d2222d37fdc", count: 4 },
        { cardId: "8f878efc-850f-43d2-a6fe-5ea8d1dd5afb", count: 2 },
        { cardId: "d26b27db-a567-4631-b4b6-7294222fbdd1", count: 4 },
        { cardId: "efb0394c-2a45-4dd8-bca3-08704056fa31", count: 3 },
        { cardId: "bd4ad383-8c40-4dda-bc9c-ba8a001d6882", count: 1 },
        { cardId: "9e2adca5-f39c-4a09-bcce-8238ebac2c4a", count: 1 },
        { cardId: "72897780-094d-4a21-8b1c-419a9defd2fb", count: 3 },
        { cardId: "44503105-3e13-408d-a44f-37d503c61d72", count: 2 },
        { cardId: "14d2979d-5728-42d7-a027-0eb1f754655d", count: 2 },
        { cardId: "616d6013-24f4-4999-9bf3-5b0764e52fa6", count: 1 },
        { cardId: "39451b4d-cd7a-40da-b457-cb51b609173f", count: 1 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 18 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 6 },
      ],
    },
  B: {
      name: "soak-mixed-1966591881",
      archetype: "soak/WRU",
      seed: 1966591881,
      colors: ["W","R","U"],
      cards: [
        { cardId: "50608184-90d3-43d2-a221-deb186c78323", count: 3 },
        { cardId: "f5f4dd28-f4ae-4d39-b9b8-6ebfd63c93fe", count: 4 },
        { cardId: "2837888c-bfa8-4955-9334-0605ad409f7e", count: 1 },
        { cardId: "c61fe162-2202-4e56-9ba0-393547f9875f", count: 2 },
        { cardId: "4c0a0448-b9d6-43a0-8549-64066dac63f0", count: 3 },
        { cardId: "7744bae4-a8b7-44a5-9b4c-0048ad4cc448", count: 2 },
        { cardId: "fd8722e1-9c41-4037-ab7e-47e2aa9858a0", count: 2 },
        { cardId: "14d2979d-5728-42d7-a027-0eb1f754655d", count: 1 },
        { cardId: "d26b27db-a567-4631-b4b6-7294222fbdd1", count: 4 },
        { cardId: "bbb6867f-7186-41de-9828-21be469178c1", count: 2 },
        { cardId: "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7", count: 2 },
        { cardId: "8c34b089-aad1-476e-958a-3077bf1bbb51", count: 3 },
        { cardId: "76ec76b9-da0f-4b9d-ad0a-d734052a5f2b", count: 2 },
        { cardId: "31f15274-301b-47c5-ba19-0ced04520878", count: 2 },
        { cardId: "5ccb57e1-ca94-4b5a-8e5f-b8b5e692cfb9", count: 1 },
        { cardId: "67f43ac6-2a58-4b53-b5d7-0330e2a252e2", count: 2 },
        { cardId: "e9f5feb2-2c1a-46ce-885a-4f378d7d10af", count: 2 },
        { cardId: "b0af0c54-2a59-4075-8543-d41ff20c4c87", count: 4 },
        { cardId: "39451b4d-cd7a-40da-b457-cb51b609173f", count: 1 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 4 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 6 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 7 },
      ],
    },
};

/** Seed 3434778477. */
export const PINNED_3434778477: PinnedMatchup = {
  A: {
      name: "soak-mixed-3434778477",
      archetype: "soak/UR",
      seed: 3434778477,
      colors: ["U","R"],
      cards: [
        { cardId: "41960d32-ddb5-42be-94b2-3a2e77ca148d", count: 4 },
        { cardId: "de3dcb5d-775a-479f-99f5-d1883ed9b1b5", count: 1 },
        { cardId: "44c5f8e1-d9b8-4067-a60a-1ecc8bd11145", count: 2 },
        { cardId: "2037659f-2efe-4321-afaf-961bbec35e9e", count: 2 },
        { cardId: "f9db72dc-9a5b-48a4-a86e-7464d9a2166a", count: 4 },
        { cardId: "a1f55890-31c5-4ed4-a2cd-7a4a9f05f8ca", count: 4 },
        { cardId: "6ad8011d-3471-4369-9d68-b264cc027487", count: 1 },
        { cardId: "7af75024-6c9b-4844-aeb6-81de25464822", count: 2 },
        { cardId: "83101ba8-a569-4827-8c53-9ca0dfcd59a7", count: 4 },
        { cardId: "6c326439-5620-4ec6-a56a-fe9c3d5d2a46", count: 4 },
        { cardId: "e018773f-95b3-49a3-9674-6f04ddef2092", count: 3 },
        { cardId: "273b339c-964b-4a18-8eb5-ceb8abcdfd9e", count: 1 },
        { cardId: "42b8aa14-10bc-4bd6-88d9-4bb287eadd19", count: 1 },
        { cardId: "2effcd1c-5833-4e0e-bb67-2d2ffb22a014", count: 1 },
        { cardId: "05d24b0c-904a-46b6-b42a-96a4d91a0dd4", count: 4 },
        { cardId: "394c6de5-7957-4a0b-a6b9-ee0c707cd022", count: 4 },
        { cardId: "79f94050-d850-41ca-b1db-5ae0cf743f0a", count: 3 },
        { cardId: "bf75a3d1-f184-4b48-a913-21caee1db084", count: 2 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 7 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 6 },
      ],
    },
  B: {
      name: "soak-mixed--345086910",
      archetype: "soak/R",
      seed: -345086910,
      colors: ["R"],
      cards: [
        { cardId: "50608184-90d3-43d2-a221-deb186c78323", count: 1 },
        { cardId: "1cb0610b-a731-42c2-b93f-0a29f63cebf4", count: 4 },
        { cardId: "7194a262-5e7a-4c12-b271-2bc5e0799477", count: 4 },
        { cardId: "8d98d674-6811-4d45-b22a-63792e272a2b", count: 1 },
        { cardId: "53c730c6-2f8c-4af8-b400-b9d573a71e60", count: 3 },
        { cardId: "de3dcb5d-775a-479f-99f5-d1883ed9b1b5", count: 4 },
        { cardId: "893fed41-c144-433f-af88-bc7d419b7fb3", count: 3 },
        { cardId: "21d700e8-0255-418e-96a0-6fe05b3f836d", count: 3 },
        { cardId: "1cf51f50-24e4-48d0-95b3-1dad3ffa4bf5", count: 2 },
        { cardId: "1a4ffc1e-2f5e-446a-b1e8-32385b3c083b", count: 1 },
        { cardId: "a1f55890-31c5-4ed4-a2cd-7a4a9f05f8ca", count: 4 },
        { cardId: "f90fe86c-5cca-483b-93c2-6e856fa01c88", count: 1 },
        { cardId: "6c5cbab6-ee27-46f5-97a7-df85698d1e9f", count: 2 },
        { cardId: "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7", count: 1 },
        { cardId: "27b047e3-0d41-45e2-98e9-9391d7923a1e", count: 2 },
        { cardId: "a75445d3-1303-4bb5-89ad-26ea93fecd48", count: 4 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 20 },
      ],
    },
};

/** Seed 113343071. */
export const PINNED_113343071: PinnedMatchup = {
  A: {
      name: "soak-mixed-113343071",
      archetype: "soak/B",
      seed: 113343071,
      colors: ["B"],
      cards: [
        { cardId: "1cf51f50-24e4-48d0-95b3-1dad3ffa4bf5", count: 2 },
        { cardId: "0c936582-d4c0-4da8-bc7e-49da5a433939", count: 2 },
        { cardId: "b91c8946-591b-4c0d-a37e-36803df40db7", count: 1 },
        { cardId: "4c0a0448-b9d6-43a0-8549-64066dac63f0", count: 4 },
        { cardId: "3525e263-e29a-49bf-a29f-fb3ce43bbd33", count: 4 },
        { cardId: "cde26d69-f3e7-4dd0-a53b-cd0ec812d717", count: 2 },
        { cardId: "1a4ffc1e-2f5e-446a-b1e8-32385b3c083b", count: 4 },
        { cardId: "932708ae-9d5c-4561-aa8b-0d2222d37fdc", count: 4 },
        { cardId: "a2529491-7389-4cfa-92d2-145eda779603", count: 2 },
        { cardId: "8c34b089-aad1-476e-958a-3077bf1bbb51", count: 2 },
        { cardId: "c97361b5-af16-4a7b-af85-a429dbaf4ad2", count: 2 },
        { cardId: "feb244f8-bcb1-44cf-9940-2719221a7309", count: 3 },
        { cardId: "66e8f7f8-3a6d-46ba-837c-b9713ddf7f40", count: 2 },
        { cardId: "616d6013-24f4-4999-9bf3-5b0764e52fa6", count: 2 },
        { cardId: "a4580a1d-141e-449b-9018-e0258130634b", count: 4 },
        { cardId: "1bd3e453-aa21-4ee6-95c2-d6d920ee8e7a", count: 2 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 18 },
      ],
    },
  B: {
      name: "soak-mixed-555061616",
      archetype: "soak/RU",
      seed: 555061616,
      colors: ["R","U"],
      cards: [
        { cardId: "52e439d0-a263-4d53-9ae3-fa1f8aa8293e", count: 3 },
        { cardId: "38cfe4a0-6ead-435b-9f86-928205c0a52c", count: 2 },
        { cardId: "a1f55890-31c5-4ed4-a2cd-7a4a9f05f8ca", count: 3 },
        { cardId: "e4bcd4ea-e7cd-4471-8f3b-18bb51d3d70c", count: 3 },
        { cardId: "76ec76b9-da0f-4b9d-ad0a-d734052a5f2b", count: 1 },
        { cardId: "e366afb3-c447-4bde-b358-41c8568142d5", count: 4 },
        { cardId: "44c5f8e1-d9b8-4067-a60a-1ecc8bd11145", count: 4 },
        { cardId: "2f01c3d9-e0fc-4cdf-b4db-daeb8bb24bc3", count: 3 },
        { cardId: "9d08af23-9f4a-4097-9abc-3b17475ab744", count: 4 },
        { cardId: "66e8f7f8-3a6d-46ba-837c-b9713ddf7f40", count: 4 },
        { cardId: "d55f6c70-321f-4fb4-bd33-0850ae1a7c36", count: 3 },
        { cardId: "144119bc-7fd1-45c5-9e29-f742e7c255ac", count: 1 },
        { cardId: "2f4ad084-2062-44c0-9975-15f100204531", count: 3 },
        { cardId: "394c6de5-7957-4a0b-a6b9-ee0c707cd022", count: 1 },
        { cardId: "6db442e5-fbcc-4456-a4c5-bea1aee3fc8e", count: 3 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 11 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 7 },
      ],
    },
};

/** Every pinned matchup, by the seed it was found at. */
export const PINNED_MATCHUPS: Readonly<Record<number, PinnedMatchup>> = Object.freeze({
  4222011655: PINNED_4222011655,
  1390617766: PINNED_1390617766,
  3434778477: PINNED_3434778477,
  113343071: PINNED_113343071,
});

/** See {@link PinnedIdentity} — cards from BOTH decks, or the row is not pinned. */
export const PINNED_IDENTITIES: Readonly<Record<number, PinnedIdentity>> = Object.freeze({
  // A: the CR 704.5f interaction (Blood Artist held up by a Machete, sacrificed
  // to Costly Plunder's additional cost). B: the Aura that set the toughness.
  4222011655: ['Blood Artist', 'Trusty Machete', 'Costly Plunder', 'Weakness'],
  // A: the copy spell and the real spell under it. B: a creature only this
  // opponent runs, so substituting either deck breaks the row.
  1390617766: ['Twincast', 'Dream Twist', 'Frolicking Familiar'],
  // Reverberate is in BOTH decks here, which is why it cannot identify either:
  // Invoke the Firemind is A's alone and Font of Mythos is B's alone.
  3434778477: ['Reverberate', 'Invoke the Firemind', 'Font of Mythos'],
  // The two copy spells are both in B; Heraldic Banner is A's, and adding it is
  // what turned this row from decorative into a guard (see PinnedIdentity).
  113343071: ['Reverberate', "Narset's Reversal", 'Heraldic Banner'],
});
