/**
 * THE DECKLISTS BEHIND THE PINNED SOAK ROWS (`soak.test.ts`).
 *
 * A pinned regression replays one game, and a game is (decks × seed). The decks
 * half used to be regenerated by sampling the pool from the seed — which meant
 * every pool change silently re-dealt every pinned row onto a different match.
 * Adding two cards in DESIGN §3.35 did exactly that to three of the four rows,
 * and an 8,000-game hunt with the fix reverted did not re-deal the copy mirror
 * once. A regression that cannot be re-found is a regression that has stopped
 * being tested.
 *
 * So the decks are recorded here, verbatim, as the generator produced them on
 * the day each bug was found. Card ids are Scryfall UUIDs and are stable across
 * pool churn — only the SAMPLING moved, never the cards themselves.
 *
 * ⚠️ Do not "tidy" these lists. They are evidence, not configuration: each one is
 * the exact 60 cards that produced a specific engine defect, and a card removed
 * from one is a row that can no longer prove its fix holds.
 */
import type { SoakDeck } from './soak-decks.js';

/** One pinned matchup: the two decklists a pinned seed originally dealt. */
export interface PinnedMatchup {
  readonly A: SoakDeck;
  readonly B: SoakDeck;
}

/** Seed 4222011655. */
export const PINNED_4222011655: PinnedMatchup = {
  A: {
      name: "soak-mixed-4222011655",
      archetype: "soak/WB",
      seed: 4222011655,
      colors: ["W","B"],
      cards: [
        { cardId: "dd70d439-bd60-43d1-ac26-13b744cc4a37", count: 1 },
        { cardId: "98423a34-f044-4811-b288-56981d604b6e", count: 1 },
        { cardId: "97b477d8-2e05-475e-8ed6-7d680cb21cd9", count: 2 },
        { cardId: "bd9e416a-89b3-4912-be9b-49fce6a93dc9", count: 1 },
        { cardId: "4b7ac066-e5c7-43e6-9e7e-2739b24a905d", count: 4 },
        { cardId: "e462e78d-2d26-4a2d-8d8f-5f31abe5c924", count: 1 },
        { cardId: "8cdfd9df-4783-4138-a286-828a97f516aa", count: 3 },
        { cardId: "394fae8f-3757-4e08-b97c-5d7c451f4e72", count: 3 },
        { cardId: "b693c3de-2eaf-4850-b405-e79d00adefda", count: 2 },
        { cardId: "a02e1ca7-23c5-41e3-a744-72fc9e9dd8ba", count: 3 },
        { cardId: "f2ccc9e8-8e92-4f8c-8728-8c748630e0dd", count: 2 },
        { cardId: "42b2db4c-4a1d-436f-9eeb-53a04db46c58", count: 4 },
        { cardId: "452e3f5f-ce17-4682-966b-5cc100210aee", count: 4 },
        { cardId: "f62cabf0-df0d-4c4f-a93a-9340967d1775", count: 1 },
        { cardId: "310f141c-7f37-4729-aed6-dd9c09db448d", count: 2 },
        { cardId: "e6e6fce8-0f6a-4b84-865e-d4e4a4182f9f", count: 2 },
        { cardId: "2672e0ca-8d5c-449f-8483-35d0e697fbb2", count: 1 },
        { cardId: "a4580a1d-141e-449b-9018-e0258130634b", count: 1 },
        { cardId: "42bf259d-4bb9-49c3-b4ec-223dca62f4d6", count: 1 },
        { cardId: "a75445d3-1303-4bb5-89ad-26ea93fecd48", count: 4 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 7 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 10 },
      ],
    },
  B: {
      name: "soak-mixed--596499928",
      archetype: "soak/UB",
      seed: -596499928,
      colors: ["U","B"],
      cards: [
        { cardId: "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7", count: 1 },
        { cardId: "02500f21-6e15-423e-93ff-891e09fe9904", count: 4 },
        { cardId: "b166b670-febc-4821-855e-f8d465644c03", count: 2 },
        { cardId: "8fcf50cd-e6d0-4516-850f-d42ee75dcc3a", count: 1 },
        { cardId: "feb244f8-bcb1-44cf-9940-2719221a7309", count: 4 },
        { cardId: "59e7f2ae-4535-4191-98be-3e65b6b2befa", count: 1 },
        { cardId: "ed228f67-3adf-46d4-ac45-e0278592850d", count: 4 },
        { cardId: "f90fe86c-5cca-483b-93c2-6e856fa01c88", count: 3 },
        { cardId: "44c5f8e1-d9b8-4067-a60a-1ecc8bd11145", count: 1 },
        { cardId: "f07a24c0-bf3c-4733-9473-c6be3b16950e", count: 4 },
        { cardId: "23745133-e5e2-4ce3-b94a-73d0d3d8a013", count: 2 },
        { cardId: "77637eff-2963-4402-88f3-ca346f762fc8", count: 4 },
        { cardId: "3378fef3-4d8c-4d9e-a338-4abb6f70d410", count: 2 },
        { cardId: "c174dcbb-03a0-439c-b3d8-ed61bd46dc67", count: 1 },
        { cardId: "765863c8-1be0-4bb1-9e9c-db7701cffde3", count: 2 },
        { cardId: "868e6e68-4367-4073-a864-235d5961ae56", count: 4 },
        { cardId: "616d6013-24f4-4999-9bf3-5b0764e52fa6", count: 1 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 9 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 10 },
      ],
    },
};

/** Seed 1390617766. */
export const PINNED_1390617766: PinnedMatchup = {
  A: {
      name: "soak-mixed-1390617766",
      archetype: "soak/UB",
      seed: 1390617766,
      colors: ["U","B"],
      cards: [
        { cardId: "d569d969-ce39-4314-b5f0-76b45f5c4c7f", count: 2 },
        { cardId: "41c84665-1f99-40ab-aaca-1188649eb263", count: 3 },
        { cardId: "cde26d69-f3e7-4dd0-a53b-cd0ec812d717", count: 4 },
        { cardId: "a2529491-7389-4cfa-92d2-145eda779603", count: 3 },
        { cardId: "932708ae-9d5c-4561-aa8b-0d2222d37fdc", count: 4 },
        { cardId: "8f878efc-850f-43d2-a6fe-5ea8d1dd5afb", count: 2 },
        { cardId: "d26b27db-a567-4631-b4b6-7294222fbdd1", count: 4 },
        { cardId: "efb0394c-2a45-4dd8-bca3-08704056fa31", count: 3 },
        { cardId: "bd4ad383-8c40-4dda-bc9c-ba8a001d6882", count: 1 },
        { cardId: "9e2adca5-f39c-4a09-bcce-8238ebac2c4a", count: 1 },
        { cardId: "72897780-094d-4a21-8b1c-419a9defd2fb", count: 3 },
        { cardId: "44503105-3e13-408d-a44f-37d503c61d72", count: 2 },
        { cardId: "14d2979d-5728-42d7-a027-0eb1f754655d", count: 2 },
        { cardId: "616d6013-24f4-4999-9bf3-5b0764e52fa6", count: 1 },
        { cardId: "39451b4d-cd7a-40da-b457-cb51b609173f", count: 1 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 18 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 6 },
      ],
    },
  B: {
      name: "soak-mixed-1966591881",
      archetype: "soak/WRU",
      seed: 1966591881,
      colors: ["W","R","U"],
      cards: [
        { cardId: "50608184-90d3-43d2-a221-deb186c78323", count: 3 },
        { cardId: "f5f4dd28-f4ae-4d39-b9b8-6ebfd63c93fe", count: 4 },
        { cardId: "2837888c-bfa8-4955-9334-0605ad409f7e", count: 1 },
        { cardId: "c61fe162-2202-4e56-9ba0-393547f9875f", count: 2 },
        { cardId: "4c0a0448-b9d6-43a0-8549-64066dac63f0", count: 3 },
        { cardId: "7744bae4-a8b7-44a5-9b4c-0048ad4cc448", count: 2 },
        { cardId: "fd8722e1-9c41-4037-ab7e-47e2aa9858a0", count: 2 },
        { cardId: "14d2979d-5728-42d7-a027-0eb1f754655d", count: 1 },
        { cardId: "d26b27db-a567-4631-b4b6-7294222fbdd1", count: 4 },
        { cardId: "bbb6867f-7186-41de-9828-21be469178c1", count: 2 },
        { cardId: "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7", count: 2 },
        { cardId: "8c34b089-aad1-476e-958a-3077bf1bbb51", count: 3 },
        { cardId: "76ec76b9-da0f-4b9d-ad0a-d734052a5f2b", count: 2 },
        { cardId: "31f15274-301b-47c5-ba19-0ced04520878", count: 2 },
        { cardId: "5ccb57e1-ca94-4b5a-8e5f-b8b5e692cfb9", count: 1 },
        { cardId: "67f43ac6-2a58-4b53-b5d7-0330e2a252e2", count: 2 },
        { cardId: "e9f5feb2-2c1a-46ce-885a-4f378d7d10af", count: 2 },
        { cardId: "b0af0c54-2a59-4075-8543-d41ff20c4c87", count: 4 },
        { cardId: "39451b4d-cd7a-40da-b457-cb51b609173f", count: 1 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 4 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 6 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 7 },
      ],
    },
};

/** Seed 3434778477. */
export const PINNED_3434778477: PinnedMatchup = {
  A: {
      name: "soak-mixed-3434778477",
      archetype: "soak/UR",
      seed: 3434778477,
      colors: ["U","R"],
      cards: [
        { cardId: "41960d32-ddb5-42be-94b2-3a2e77ca148d", count: 4 },
        { cardId: "de3dcb5d-775a-479f-99f5-d1883ed9b1b5", count: 1 },
        { cardId: "44c5f8e1-d9b8-4067-a60a-1ecc8bd11145", count: 2 },
        { cardId: "2037659f-2efe-4321-afaf-961bbec35e9e", count: 2 },
        { cardId: "f9db72dc-9a5b-48a4-a86e-7464d9a2166a", count: 4 },
        { cardId: "a1f55890-31c5-4ed4-a2cd-7a4a9f05f8ca", count: 4 },
        { cardId: "6ad8011d-3471-4369-9d68-b264cc027487", count: 1 },
        { cardId: "7af75024-6c9b-4844-aeb6-81de25464822", count: 2 },
        { cardId: "83101ba8-a569-4827-8c53-9ca0dfcd59a7", count: 4 },
        { cardId: "6c326439-5620-4ec6-a56a-fe9c3d5d2a46", count: 4 },
        { cardId: "e018773f-95b3-49a3-9674-6f04ddef2092", count: 3 },
        { cardId: "273b339c-964b-4a18-8eb5-ceb8abcdfd9e", count: 1 },
        { cardId: "42b8aa14-10bc-4bd6-88d9-4bb287eadd19", count: 1 },
        { cardId: "2effcd1c-5833-4e0e-bb67-2d2ffb22a014", count: 1 },
        { cardId: "05d24b0c-904a-46b6-b42a-96a4d91a0dd4", count: 4 },
        { cardId: "394c6de5-7957-4a0b-a6b9-ee0c707cd022", count: 4 },
        { cardId: "79f94050-d850-41ca-b1db-5ae0cf743f0a", count: 3 },
        { cardId: "bf75a3d1-f184-4b48-a913-21caee1db084", count: 2 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 7 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 6 },
      ],
    },
  B: {
      name: "soak-mixed--345086910",
      archetype: "soak/R",
      seed: -345086910,
      colors: ["R"],
      cards: [
        { cardId: "50608184-90d3-43d2-a221-deb186c78323", count: 1 },
        { cardId: "1cb0610b-a731-42c2-b93f-0a29f63cebf4", count: 4 },
        { cardId: "7194a262-5e7a-4c12-b271-2bc5e0799477", count: 4 },
        { cardId: "8d98d674-6811-4d45-b22a-63792e272a2b", count: 1 },
        { cardId: "53c730c6-2f8c-4af8-b400-b9d573a71e60", count: 3 },
        { cardId: "de3dcb5d-775a-479f-99f5-d1883ed9b1b5", count: 4 },
        { cardId: "893fed41-c144-433f-af88-bc7d419b7fb3", count: 3 },
        { cardId: "21d700e8-0255-418e-96a0-6fe05b3f836d", count: 3 },
        { cardId: "1cf51f50-24e4-48d0-95b3-1dad3ffa4bf5", count: 2 },
        { cardId: "1a4ffc1e-2f5e-446a-b1e8-32385b3c083b", count: 1 },
        { cardId: "a1f55890-31c5-4ed4-a2cd-7a4a9f05f8ca", count: 4 },
        { cardId: "f90fe86c-5cca-483b-93c2-6e856fa01c88", count: 1 },
        { cardId: "6c5cbab6-ee27-46f5-97a7-df85698d1e9f", count: 2 },
        { cardId: "00e35322-1a9a-41e3-9ce1-359c8eaa3bc7", count: 1 },
        { cardId: "27b047e3-0d41-45e2-98e9-9391d7923a1e", count: 2 },
        { cardId: "a75445d3-1303-4bb5-89ad-26ea93fecd48", count: 4 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 20 },
      ],
    },
};

/** Seed 113343071. */
export const PINNED_113343071: PinnedMatchup = {
  A: {
      name: "soak-mixed-113343071",
      archetype: "soak/B",
      seed: 113343071,
      colors: ["B"],
      cards: [
        { cardId: "1cf51f50-24e4-48d0-95b3-1dad3ffa4bf5", count: 2 },
        { cardId: "0c936582-d4c0-4da8-bc7e-49da5a433939", count: 2 },
        { cardId: "b91c8946-591b-4c0d-a37e-36803df40db7", count: 1 },
        { cardId: "4c0a0448-b9d6-43a0-8549-64066dac63f0", count: 4 },
        { cardId: "3525e263-e29a-49bf-a29f-fb3ce43bbd33", count: 4 },
        { cardId: "cde26d69-f3e7-4dd0-a53b-cd0ec812d717", count: 2 },
        { cardId: "1a4ffc1e-2f5e-446a-b1e8-32385b3c083b", count: 4 },
        { cardId: "932708ae-9d5c-4561-aa8b-0d2222d37fdc", count: 4 },
        { cardId: "a2529491-7389-4cfa-92d2-145eda779603", count: 2 },
        { cardId: "8c34b089-aad1-476e-958a-3077bf1bbb51", count: 2 },
        { cardId: "c97361b5-af16-4a7b-af85-a429dbaf4ad2", count: 2 },
        { cardId: "feb244f8-bcb1-44cf-9940-2719221a7309", count: 3 },
        { cardId: "66e8f7f8-3a6d-46ba-837c-b9713ddf7f40", count: 2 },
        { cardId: "616d6013-24f4-4999-9bf3-5b0764e52fa6", count: 2 },
        { cardId: "a4580a1d-141e-449b-9018-e0258130634b", count: 4 },
        { cardId: "1bd3e453-aa21-4ee6-95c2-d6d920ee8e7a", count: 2 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 18 },
      ],
    },
  B: {
      name: "soak-mixed-555061616",
      archetype: "soak/RU",
      seed: 555061616,
      colors: ["R","U"],
      cards: [
        { cardId: "52e439d0-a263-4d53-9ae3-fa1f8aa8293e", count: 3 },
        { cardId: "38cfe4a0-6ead-435b-9f86-928205c0a52c", count: 2 },
        { cardId: "a1f55890-31c5-4ed4-a2cd-7a4a9f05f8ca", count: 3 },
        { cardId: "e4bcd4ea-e7cd-4471-8f3b-18bb51d3d70c", count: 3 },
        { cardId: "76ec76b9-da0f-4b9d-ad0a-d734052a5f2b", count: 1 },
        { cardId: "e366afb3-c447-4bde-b358-41c8568142d5", count: 4 },
        { cardId: "44c5f8e1-d9b8-4067-a60a-1ecc8bd11145", count: 4 },
        { cardId: "2f01c3d9-e0fc-4cdf-b4db-daeb8bb24bc3", count: 3 },
        { cardId: "9d08af23-9f4a-4097-9abc-3b17475ab744", count: 4 },
        { cardId: "66e8f7f8-3a6d-46ba-837c-b9713ddf7f40", count: 4 },
        { cardId: "d55f6c70-321f-4fb4-bd33-0850ae1a7c36", count: 3 },
        { cardId: "144119bc-7fd1-45c5-9e29-f742e7c255ac", count: 1 },
        { cardId: "2f4ad084-2062-44c0-9975-15f100204531", count: 3 },
        { cardId: "394c6de5-7957-4a0b-a6b9-ee0c707cd022", count: 1 },
        { cardId: "6db442e5-fbcc-4456-a4c5-bea1aee3fc8e", count: 3 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 11 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 7 },
      ],
    },
};

export const PINNED_3736754678: PinnedMatchup = {
  A: {
      name: "soak-mixed-3736754678",
      archetype: "soak/UB",
      seed: 3736754678,
      colors: ["U","B"],
      cards: [
        { cardId: "4f5a3293-f3e7-4f68-af6a-b478959226c1", count: 3 },
        { cardId: "b079f9db-974d-4525-a894-57b754ba9dcc", count: 4 },
        { cardId: "1444786c-fb9f-4398-b442-c7cfd6f1df40", count: 1 },
        { cardId: "edd8d1e8-be43-4c38-bb3a-83081fbaf0b5", count: 4 },
        { cardId: "bb75ec92-7c8e-47d3-a412-01d0c98321fe", count: 1 },
        { cardId: "98902dd9-f21c-4419-8205-4b9d6592bf28", count: 2 },
        { cardId: "2222f499-09f9-45a6-8255-9de79df76f1c", count: 4 },
        { cardId: "9d60f16a-0a67-4ad7-8dad-ee97cd01fb89", count: 4 },
        { cardId: "95a52cb8-e02f-477a-adb6-2bfb7836c704", count: 2 },
        { cardId: "f71a86e0-d15a-4fba-94f6-bfbaade8d837", count: 4 },
        { cardId: "693a5a97-d81e-4f4d-ab8f-5a9cabd4c685", count: 1 },
        { cardId: "18bbdc6c-b6c9-4f89-8f0a-6266e53c1fb9", count: 2 },
        { cardId: "938066de-d111-4df2-87f0-9eb72aa4cdac", count: 1 },
        { cardId: "3ac987ac-3f81-4704-b42c-651f44670641", count: 1 },
        { cardId: "3bfa5ebc-5623-4eec-89ea-dc187489ee4a", count: 1 },
        { cardId: "156df6eb-1ac9-4954-bf93-b1668096b8bd", count: 1 },
        { cardId: "e9681a54-6413-4ff4-b6b1-ee4decb25bfa", count: 1 },
        { cardId: "f8429762-e756-43e0-81b4-9d0a34270040", count: 3 },
        { cardId: "94e0ad38-31b3-46ba-9999-9b6ff57906ae", count: 3 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 9 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 8 },
      ],
    },
  B: {
      name: "soak-mixed--110185767",
      archetype: "soak/RBW",
      seed: -110185767,
      colors: ["R","B","W"],
      cards: [
        { cardId: "058490f4-0ada-45e6-b4f0-e433537f52d6", count: 2 },
        { cardId: "24a256b0-e25b-43c6-9f7a-2ad76b268d22", count: 2 },
        { cardId: "a084d0fb-8db2-4873-a2f9-e6e5fecdd38c", count: 1 },
        { cardId: "f5f80d82-d64c-466f-8874-9cfb00469f02", count: 3 },
        { cardId: "10dfc217-ae94-4ff0-bf30-7131f97aa3c9", count: 3 },
        { cardId: "06ee5eda-41a9-4cae-bb2a-b63fd450d02d", count: 2 },
        { cardId: "22a2b882-d616-495e-99f6-196031235f93", count: 2 },
        { cardId: "978cc53c-c038-4442-bd46-e0b9e8cdd924", count: 1 },
        { cardId: "fa755966-0b96-4747-ba1f-26182d265335", count: 1 },
        { cardId: "0ebd63cf-7e8c-4c8d-844d-98535d5f3039", count: 3 },
        { cardId: "f33e3b25-76f5-4263-a309-9ea97f2d8248", count: 3 },
        { cardId: "1e7162e5-8c56-457e-91eb-b8ae4d1b6adb", count: 4 },
        { cardId: "b1c6df1d-7709-41e4-a79f-0dc722600191", count: 4 },
        { cardId: "ec66b814-9c47-4d17-8c02-1d9be565c76c", count: 3 },
        { cardId: "926916ed-2f22-4ba9-9427-194886ad6c1e", count: 3 },
        { cardId: "ac07e230-0297-4e1d-bdfe-119010e0ad8e", count: 2 },
        { cardId: "a4580a1d-141e-449b-9018-e0258130634b", count: 2 },
        { cardId: "73c423b7-cab8-4e69-8070-9edbf96a6c2c", count: 3 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 6 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 4 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 6 },
      ],
    },
};

export const PINNED_3455580742: PinnedMatchup = {
  A: {
      name: "soak-mixed-3455580742",
      archetype: "soak/UW",
      seed: 3455580742,
      colors: ["U","W"],
      cards: [
        { cardId: "2fda4fe7-8b0c-489c-a000-6d358e614e34", count: 3 },
        { cardId: "31c729e2-4e55-4a14-a288-9c3473e58b88", count: 3 },
        { cardId: "2c697b0b-edba-491a-b40e-f88572a6e955", count: 3 },
        { cardId: "e672a05c-5f1a-4aa6-9398-e33df01c7c96", count: 1 },
        { cardId: "325f228e-46ff-43e2-bc1d-c2d2df443c51", count: 2 },
        { cardId: "e52464ee-df8b-41ec-af93-4b0eb004383e", count: 4 },
        { cardId: "068e7803-7c9f-43d7-b6dc-8e1390d902d0", count: 3 },
        { cardId: "48c1a040-9045-4977-84e4-695de0f886a9", count: 4 },
        { cardId: "fce74849-2e08-4d08-b387-4693f1b9f653", count: 2 },
        { cardId: "b4fb87ab-8595-459a-a5f2-087296d9b120", count: 4 },
        { cardId: "e3979b88-ac58-420a-8c03-37ea5d93d0f1", count: 2 },
        { cardId: "313e71da-ce72-4976-8286-f4495ea56485", count: 3 },
        { cardId: "cc2741d8-2c02-4acd-8ca2-55b4bf6aef1c", count: 4 },
        { cardId: "b2c6aa39-2d2a-459c-a555-fb48ba993373", count: 14 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 8 },
      ],
    },
  B: {
      name: "soak-mixed--366800535",
      archetype: "soak/RWG",
      seed: -366800535,
      colors: ["R","W","G"],
      cards: [
        { cardId: "422aca0b-8e8f-4774-9a20-6f7a1cae967e", count: 4 },
        { cardId: "489c6a2f-38b4-4ff9-95f7-431384480ed9", count: 4 },
        { cardId: "407110e9-19af-4ff5-97b2-c03225031a73", count: 2 },
        { cardId: "d3be1289-76f9-40b3-9387-b76a8b8d8797", count: 1 },
        { cardId: "ce33ef5b-a0ff-459c-a9d4-a0a00ac66b31", count: 4 },
        { cardId: "301310b3-c031-4fd3-a47e-9645b6177329", count: 1 },
        { cardId: "b32c342f-ee1a-461c-9082-d2f6d9412f54", count: 2 },
        { cardId: "71a25c69-8e57-4a44-955a-da1541bbe0fe", count: 1 },
        { cardId: "c3c3243c-e9af-4b7d-8296-f7714436e571", count: 4 },
        { cardId: "05d5a38f-5a60-46da-af1c-440e4bf7fe9e", count: 2 },
        { cardId: "9aaf0df7-5e2d-4f49-a8cb-66523be15ad6", count: 1 },
        { cardId: "0b79b30e-e7aa-490e-b130-de7533e6e13b", count: 4 },
        { cardId: "70e888f9-c583-478a-9ef0-2e89db8a8dbb", count: 4 },
        { cardId: "6389c242-2139-4f12-af30-2b080a1c5e83", count: 4 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 3 },
        { cardId: "bc71ebf6-2056-41f7-be35-b2e5c34afa99", count: 9 },
        { cardId: "b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6", count: 10 },
      ],
    },
};

export const PINNED_3679986871: PinnedMatchup = {
  A: {
      name: "soak-mixed-3679986871",
      archetype: "soak/RG",
      seed: 3679986871,
      colors: ["R","G"],
      cards: [
        { cardId: "2b7cb1a3-761e-470e-a164-6e29dd9448cd", count: 3 },
        { cardId: "7fddcd48-3efe-4b56-9d69-9659b3dc6021", count: 1 },
        { cardId: "c69742a8-cc6d-457b-8d99-81d05ab1bf0b", count: 1 },
        { cardId: "eefea84f-d657-491d-b60d-63e6a61e9eb2", count: 4 },
        { cardId: "3469d73e-6de1-4b91-83e3-b1714ac29268", count: 3 },
        { cardId: "ae115587-012d-40ff-a20d-270fabf2f8c6", count: 3 },
        { cardId: "c4e319d7-53f3-40e8-9a75-fe1fd8716733", count: 1 },
        { cardId: "05bc4236-566f-401b-b9d7-f58126fa228b", count: 3 },
        { cardId: "5503186a-46fe-4956-8ae3-5ab3343f8a93", count: 3 },
        { cardId: "4c97229f-2fc8-439a-a18b-efa09b366b70", count: 2 },
        { cardId: "8f1e75e1-a827-46c1-896f-cd8fbdf79fa8", count: 2 },
        { cardId: "2e0b23a4-5868-4dd8-ae68-846934e1bd52", count: 4 },
        { cardId: "88a68767-9822-4f15-895e-32164e2159be", count: 1 },
        { cardId: "1fa2963d-010f-491c-8ccc-3b4d4bc88398", count: 1 },
        { cardId: "339acb17-4b8e-4836-9cc5-8a0a946ebc73", count: 2 },
        { cardId: "989b5901-aeb0-4a48-8c53-3b0ec0e0deba", count: 3 },
        { cardId: "727beb1f-1445-4398-970c-e31819d54bc6", count: 2 },
        { cardId: "b33656ae-3473-4223-845f-f9147f87678b", count: 1 },
        { cardId: "33145080-077e-4231-96ca-e8b1852b6380", count: 4 },
        { cardId: "a3fb7228-e76b-4e96-a40e-20b5fed75685", count: 6 },
        { cardId: "b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6", count: 10 },
      ],
    },
  B: {
      name: "soak-mixed--57880680",
      archetype: "soak/GB",
      seed: -57880680,
      colors: ["G","B"],
      cards: [
        { cardId: "e34fa15b-4559-4a8f-aa29-5c43eb4eeef9", count: 4 },
        { cardId: "0950bfe7-2600-4e01-8f54-f03a5c023520", count: 4 },
        { cardId: "4724d00a-b93b-43fd-9c86-56f127db450b", count: 2 },
        { cardId: "eaedd5c8-03c6-4bbb-bf83-632551830bd4", count: 4 },
        { cardId: "d9482aab-6ddf-48e1-84fa-b13d5ff81e69", count: 4 },
        { cardId: "16debeb1-fb2b-4172-b6da-726416d4fb38", count: 4 },
        { cardId: "6d808a30-f1b5-484e-a90e-0a9f751ef597", count: 1 },
        { cardId: "8f56705d-eb64-4cef-b716-edbeac60bf79", count: 2 },
        { cardId: "8aaae6a3-ae3c-4b7e-82e8-69147f61ee18", count: 2 },
        { cardId: "89a60271-edfc-4bb1-83d5-4d6fa0403b19", count: 3 },
        { cardId: "a070b7af-7c85-4129-81ca-e2ec0540085e", count: 4 },
        { cardId: "f8373e5a-94bb-4aa0-bd09-13a01e0cb02a", count: 1 },
        { cardId: "88231c0d-0cc8-44ec-bf95-81d1710ac141", count: 1 },
        { cardId: "1bd3e453-aa21-4ee6-95c2-d6d920ee8e7a", count: 2 },
        { cardId: "226af626-873d-4bd2-b889-000f8316786f", count: 2 },
        { cardId: "6db442e5-fbcc-4456-a4c5-bea1aee3fc8e", count: 2 },
        { cardId: "cbab7e1f-305e-4733-aa70-b27285740925", count: 4 },
        { cardId: "61fc0fba-c285-4fad-85a6-79fd7f3f9c35", count: 1 },
        { cardId: "b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6", count: 7 },
        { cardId: "56719f6a-1a6c-4c0a-8d21-18f7d7350b68", count: 6 },
      ],
    },
};

/**
 * WHICH GAME EACH PINNED SEED IS — the cards without which a replay is not the
 * match the bug came from.
 *
 * ⚠️ This is the half of a pinned test that can fail for the RIGHT reason. "No
 * violations" is also what a replay of the WRONG game reports, so an
 * outcome-only assertion is green for two completely different reasons and
 * cannot tell them apart. That is not a hypothesis: flipping one bit of the
 * opponent-deck seed once left a pinned row passing, happily replaying a
 * different match.
 *
 * ⚠️ EVERY ENTRY MUST NAME CARDS FROM BOTH DECKS. A row that named only one
 * deck's cards is the same escape one deck deeper — swap the OTHER deck and the
 * identity assertion still passes while the game being replayed is not the one
 * the row describes. `soak.test.ts` asserts exactly that of this table ("every
 * pinned identity names cards from BOTH decks"), so a new row cannot be added
 * half-named.
 *
 * It lives HERE, beside the decklists, because a matchup's identity and its
 * decklists are one fact. Two tables that could drift is two answers to "which
 * game was this", and the weaker one is the one a green test would believe.
 */
export const PINNED_IDENTITIES: Readonly<Record<number, readonly string[]>> = Object.freeze({
  // A's half of the CR 704.5f interaction, and B's Aura: all four have to be
  // dealt into the same game for the position to exist at all.
  4222011655: ['Blood Artist', 'Trusty Machete', 'Costly Plunder', 'Weakness'],
  // The copy mirror — the copy spell, the spell underneath it, and the other
  // seat's board it was aimed across.
  1390617766: ['Twincast', 'Dream Twist', 'Goblin Piker', 'Mana Leak'],
  3434778477: ['Reverberate', 'Invoke the Firemind', 'Font of Mythos', 'Adaptive Automaton'],
  113343071: ['Reverberate', "Narset's Reversal", 'Darksteel Sentinel', 'Bone Splinters'],
  // The split-second lock (DESIGN §3.141): B's Siege Smash, the Mouser Attack!
  // it cast into its own lock, and A's side of the board it happened over.
  3736754678: ['Siege Smash', 'Mouser Attack!', 'Soldevi Simulacrum', 'Thoughtseize'],
  // The blocking cap (§3.141): B's Bristling Boar, and the two A creatures the
  // gang search paired onto it.
  3455580742: ['Bristling Boar', 'Millennial Gargoyle', 'Screeching Sliver'],
  // The moving land-drop cap (§3.141): B's Icetill Explorer — the "additional
  // land" AND "play lands from your graveyard" that made two drops legal — and
  // A's board, whose combat killed it a turn later.
  3679986871: ['Icetill Explorer', 'Mire Triton', 'Nyxborn Brute', 'Tel-Jilad Chosen'],
});

/** Every pinned matchup, by the seed it was found at. */
export const PINNED_MATCHUPS: Readonly<Record<number, PinnedMatchup>> = Object.freeze({
  4222011655: PINNED_4222011655,
  1390617766: PINNED_1390617766,
  3434778477: PINNED_3434778477,
  113343071: PINNED_113343071,
  3736754678: PINNED_3736754678,
  3455580742: PINNED_3455580742,
  3679986871: PINNED_3679986871,
});
