/**
 * Generates `assembly/generated.ts` — the AssemblyScript mirror of the layout
 * offsets, the rules constants, the card table and the decks.
 *
 * This exists so arms B and C CANNOT DRIFT. A hand-maintained copy of ~60 offsets
 * and a 19-card data table in a second language is a guaranteed source of silent
 * divergence, and a divergence here would not show up as a crash — it would show
 * up as a plausible-looking benchmark number for a program that is playing a
 * different game. One source, one generator, and an equivalence gate on top.
 *
 * Run: node codegen-layout.mjs
 */

import { writeFileSync } from 'node:fs';
import * as layout from './src/layout.mjs';
import * as spec from './src/spec.mjs';

/** Rules/encoding constants arm C needs. Layout constants come from EXPORTED_CONSTANTS. */
const SPEC_CONSTANTS = [
  'STARTING_LIFE',
  'OPENING_HAND',
  'DECK_SIZE',
  'MAX_LANDS_PER_TURN',
  'MAX_INSTANCES',
  'ACTION_CAP',
  'MAX_TURNS',
  'CAP_ACTIONS',
  'NUM_COLORS',
  'POOL_SLOTS',
  'POOL_COLORLESS',
  'COST_GENERIC',
  'KIND_LAND',
  'KIND_CREATURE',
  'KIND_BOLT',
  'KIND_PUMP',
  'KW_FLYING',
  'KW_LIFELINK',
  'KW_DEATHTOUCH',
  'KW_VIGILANCE',
  'KW_HASTE',
  'TARGET_NONE',
  'TARGET_ANY',
  'TARGET_CREATURE',
  'TIMING_SORCERY',
  'TIMING_INSTANT',
  'STEP_UNTAP',
  'STEP_UPKEEP',
  'STEP_DRAW',
  'STEP_MAIN1',
  'STEP_DECLARE_ATTACKERS',
  'STEP_DECLARE_BLOCKERS',
  'STEP_COMBAT_DAMAGE',
  'STEP_MAIN2',
  'STEP_END',
  'STEP_CLEANUP',
  'ACT_PASS',
  'ACT_PLAY_LAND',
  'ACT_TAP_FOR_MANA',
  'ACT_CAST_SPELL',
  'ACT_DECLARE_ATTACKERS',
  'ACT_DECLARE_BLOCKERS',
  'ATTACK_ALL',
  'ATTACK_PROFITABLE',
  'BLOCK_NONE',
  'BLOCK_GREEDY',
  'TARGET_PLAYER_0',
  'TARGET_NOTHING',
  'CARD_STRIDE',
  'CARD_KIND',
  'CARD_COST',
  'CARD_POWER',
  'CARD_TOUGHNESS',
  'CARD_KEYWORDS',
  'CARD_PRODUCES',
  'CARD_AMOUNT',
  'CARD_TIMING',
  'CARD_TARGET',
  'NUM_CARDS',
];

const lines = [];
lines.push('// GENERATED by codegen-layout.mjs — DO NOT EDIT.');
lines.push('// Source of truth: src/layout.mjs and src/spec.mjs. Re-run the generator instead.');
lines.push('');

for (const [name, value] of Object.entries(layout.EXPORTED_CONSTANTS)) {
  if (!Number.isInteger(value)) throw new Error(`layout constant ${name} is not an integer: ${value}`);
  lines.push(`export const ${name}: i32 = ${value};`);
}
lines.push('');
for (const name of SPEC_CONSTANTS) {
  const value = spec[name];
  if (!Number.isInteger(value)) throw new Error(`spec constant ${name} is missing or not an integer: ${value}`);
  lines.push(`export const ${name}: i32 = ${value};`);
}

lines.push('');
const table = spec.flatCardTable();
lines.push(`export const CARD_TABLE: StaticArray<i32> = [${table.join(',')}];`);
lines.push('');
lines.push(`export const DECK0: StaticArray<i32> = [${spec.DECKS[0].join(',')}];`);
lines.push(`export const DECK1: StaticArray<i32> = [${spec.DECKS[1].join(',')}];`);
lines.push('');

writeFileSync(new URL('./assembly/generated.ts', import.meta.url), lines.join('\n') + '\n');
console.log(
  `assembly/generated.ts written: ${Object.keys(layout.EXPORTED_CONSTANTS).length} layout + ${SPEC_CONSTANTS.length} spec constants, ` +
    `${spec.NUM_CARDS} cards, arena ${layout.ARENA_SIZE} i32 (${(layout.ARENA_SIZE * 4) / 1024} KiB)`,
);
